### ISSUE TITLE
Error 404 when asking for more than 6 previous issues of Bulletin A

### ISSUE THREAD

**Issue by nealmcb** [fanf2/bulletin-a#1]
Something seems to have changed about the availability of archival bulletins. While the example in the README shows successful retrievals of 50 previous issues of Bulletin A, when I use any argument over 6, I get an error:

```
$ cargo run 7
    Finished dev [unoptimized + debuginfo] target(s) in 0.01s
     Running `target/debug/bulletin-a 7`
fetching https://datacenter.iers.org/data/6/bulletina-xxxv-011.txt
Error: failed to get https://datacenter.iers.org/data/6/bulletina-xxxv-011.txt

Caused by:
    [22] HTTP response code said error (The requested URL returned error: 404)
```

Here I show just the fetches and errors from a number of runs. If there is no Error, then it ran fine.

Note that the code knows how to find Bulletin A based on the (I'm not kidding) _roman numerals_ for the number of years since their initial epoch for this sort of archival (1987).  But they seem to be failing to serve more than 6 weeks back (https://datacenter.iers.org/data/6/bulletina-xxxv-011.txt from 2022-03-17 and before)

```
fetching https://datacenter.iers.org/data/6/bulletina-xxxv-017.txt
fetching https://datacenter.iers.org/data/6/bulletina-xxxiv-050.txt
Error: failed to get https://datacenter.iers.org/data/6/bulletina-xxxiv-050.txt
fetching https://datacenter.iers.org/data/6/bulletina-xxxiv-020.txt
Error: failed to get https://datacenter.iers.org/data/6/bulletina-xxxiv-020.txt
fetching https://datacenter.iers.org/data/6/bulletina-xxxv-016.txt
fetching https://datacenter.iers.org/data/6/bulletina-xxxv-001.txt
Error: failed to get https://datacenter.iers.org/data/6/bulletina-xxxv-001.txt
fetching https://datacenter.iers.org/data/6/bulletina-xxxv-002.txt
Error: failed to get https://datacenter.iers.org/data/6/bulletina-xxxv-002.txt
fetching https://datacenter.iers.org/data/6/bulletina-xxxv-015.txt
fetching https://datacenter.iers.org/data/6/bulletina-xxxv-014.txt
fetching https://datacenter.iers.org/data/6/bulletina-xxxv-008.txt
Error: failed to get https://datacenter.iers.org/data/6/bulletina-xxxv-008.txt
fetching https://datacenter.iers.org/data/6/bulletina-xxxv-013.txt
fetching https://datacenter.iers.org/data/6/bulletina-xxxv-011.txt
Error: failed to get https://datacenter.iers.org/data/6/bulletina-xxxv-011.txt
fetching https://datacenter.iers.org/data/6/bulletina-xxxv-012.txt
fetching https://datacenter.iers.org/data/6/bulletina-xxxv-011.txt
Error: failed to get https://datacenter.iers.org/data/6/bulletina-xxxv-011.txt
```

I don't know if this is a glitch in archival, or a change that the code needs to be aware of, but I figured I'd at least document it for others, as we track the most interesting period in earth rotation in decades, and the possibility of a negative leap second.

After some googling, I also ran across this, which also just lists the last 6 issues:

[BULLETIN A \- all available versions](https://datacenter.iers.org/availableVersions.php?id=6)

Note that a random sprinkling of them have been saved from a few crawls by the Internet Archive over the last year:

[Wayback Machine search for archived Bulletin A](https://web.archive.org/web/*/https://datacenter.iers.org/data/6/*)

**Comment by fanf2** [comment]
Yes, there was a problem with datacenter.iers.org a few weeks ago (it was completely down for a while) and when it came back most of the archive was missing. Vexing!

Since I don't know where else to get old editions from other than my own copies, I've committed them to this repository, so you will only need to fetch new issues that I have not yet synced.

**Comment by fanf2** [comment]
PS. my archive goes back to 2005 which I think (if I remember correctly, which I might not) was all that was available when I fetched them.

**Comment by nealmcb** [comment]
Wow that was fast - thanks!!

And this is all just shortly after maia.usno.navy.mil came back online, as announced in Bulletin A itself as of 10 February 2022: https://github.com/fanf2/bulletin-a/blob/main/bula/2022/006 

Hopefully we can dig out some other old ones.....
